version: "3"

services:
  free-searches-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app/"
    env_file:
      - ".env"
    depends_on:
      - tor
  tor:
    ports:
        - '9050:9050'
    image: osminogin/tor-simple